Dev
AutomationSolutionz/Zeuz_Python_Node pull request #164
Opened 2022-04-16 11:14 UTC by Muntasib-creator

## PR Type
Bug Fix, Feature,  Refactor, New Actions, New Report structure

## PR Checklist

- [x ] Tests for the changes have been added / updated.
- [x ] Documentation comments have been added / updated.
- [ x] A changelog entry has been made.
- [x ] Version number has been updated.
- [x ] Required modules have been added to respective "requirements*.txt" files.

## Overview
- [Add] Added capability for handling alert as desired.
- [Add] Added action read scanned pdf
- [Add] email_attachment feature is added into email_read action
- [Add] zeuz_current_tc and zeuz_current_step variables are added
- [Add] Add capability for handling alert as desired.
- [Add] Added 4 new actions: 
  - Attachments upload to Testcase
  - Attachments upload to Step
  - Attachments upload to Global
  - Disable steps

- [Change] openpyxl is made default for excel_read
- [Change] Reporting structure is changed
- [Fix] --log_dir is fixed
- [Fix] import pyautogui fix for ui-less machine
- [Remove] SSL validation is bypassed while installing webdriver

2022-04-16 15:33 UTC, Oytizzo approved these changes

2022-04-16 15:53 UTC, Oytizzo requested changes

2022-04-16 15:53 UTC, Oytizzo commented on Framework/Built_In_Automation/Web/Selenium/BuiltInFunctions.py
> +            options.add_argument("--no-sandbox")
duplicate

2022-04-17 06:57 UTC, sazid commented on Framework/Built_In_Automation/Web/Selenium/BuiltInFunctions.py
> +                    if right.strip().lower() in ("accept", "yes", "ok"):
@Muntasib-creator @Oytizzo there should be another `else` branch to include whatever desired capability the user may provide in the future. The key will be the left and the value will be the right. Can go into next release.

2022-04-17 07:00 UTC, sazid commented on requirements.txt
> +pytesseract
New requirements must be added to all platform specific requirement files as well - `requirements-win.txt`, `requirements-mac.txt`, `requirements-linux.txt`

2022-04-18 11:01 UTC, sazid approved these changes

2022-04-18 11:01 UTC, merged