Database Bug fix
AutomationSolutionz/Zeuz_Python_Node pull request #203
Opened 2022-06-30 10:04 UTC by Raisa2773

## PR Type
 Database bug fixed
 Bug fix
PR_TYPE

## PR Checklist

- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] A changelog entry has been made.
- [ ] Version number has been updated.
- [ ] Required modules have been added to respective "requirements*.txt" files.
- [ ] Relevant Test Cases added to this description (below).
- [ ] (Team) Label with affected action categories and server status.

## Overview
 sid and service name is needed for oracle only. previously node gave error for not providing sid and service name in other database types too. Now added a check for oracle.
 N/A

2022-06-30 12:34 UTC, Muntasib-creator requested changes

2022-06-30 12:34 UTC, Muntasib-creator commented on Framework/Built_In_Automation/Database/BuiltInFunctions.py
> +        if "oracle" in db_type:
```python
if "oracle" in db_type.lower():
 ```

2022-06-30 12:34 UTC, Muntasib-creator commented on Framework/Built_In_Automation/Web/Selenium/BuiltInFunctions.py
> +        print(f"\033[93m{browser_options}\033[0m")
revert this line

2022-07-04 04:35 UTC, Muntasib-creator approved these changes

2022-07-04 05:01 UTC, Raisa2773 commented
@Muntasib-creator CHANGELOG.md has been updated

2022-07-04 05:09 UTC, merged