Nodecli work
AutomationSolutionz/Zeuz_Python_Node pull request #325
Opened 2023-06-08 11:38 UTC by rfnshare

## PR Type

Feature

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] A changelog entry has been made.
- [ ] Version number has been updated.
- [x] Required modules have been added to respective "requirements*.txt" files.
- [ ] Relevant Test Cases added to this description (below).
- [ ] (Team) Label with affected action categories and semver status.

## Overview

Added auto log delete & module update time interval 

No

2023-06-14 11:46 UTC, Muntasib-creator commented on Framework/settings.conf
> -edge_path =
revert as before

2023-06-14 11:46 UTC, Muntasib-creator commented on Framework/settings.conf
> +Window = ""
revert as before

2023-06-21 07:57 UTC, sazid commented
@rfnshare you need to describe the feature and put appropriate title.

2023-07-15 06:07 UTC, sazid requested changes

2023-07-15 06:07 UTC, sazid commented on requirements.txt
> +configobj
We don't need additional configobj to accomplish this. There is already a builtin config handler module inside node for these use cases, please use that.

2023-08-28 06:59 UTC, sazid approved these changes

2023-08-28 07:02 UTC, merged