Added new action named Change_Attribute_Value
AutomationSolutionz/Zeuz_Python_Node pull request #326
Opened 2023-06-11 17:39 UTC by Towshik

## PR Type

PR_TYPE

## PR Checklist

- [* ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] A changelog entry has been made.
- [ ] Version number has been updated.
- [ ] Required modules have been added to respective "requirements*.txt" files.
- [* ] Relevant Test Cases added to this description (below).
- [ ] (Team) Label with affected action categories and server status.

## Overview

Added a new action called Change_Attribute_Value

## Test Cases
- [TEST-5648](https://qa.zeuz.ai/Home/ManageTestCases/Edit/TEST-5648/)

2023-06-14 08:48 UTC, Muntasib-creator requested changes

2023-06-14 08:48 UTC, Muntasib-creator commented on Framework/Built_In_Automation/Web/Selenium/BuiltInFunctions.py
> +        errMsg = "Could not select/click your element."
Wrong error message and passed message

2023-06-14 08:48 UTC, Muntasib-creator commented on Framework/Built_In_Automation/Web/Selenium/BuiltInFunctions.py
> +        errMsg = "Could not select/click your element."
@Towshik

2023-06-14 09:21 UTC, Towshik commented on Framework/Built_In_Automation/Web/Selenium/BuiltInFunctions.py
> +        errMsg = "Could not select/click your element."
Fixed the messages

2023-06-21 07:59 UTC, sazid commented
@Towshik fix the pr description.

2023-06-21 08:16 UTC, Towshik commented
> @Towshik fix the pr description.

Done vai

2023-06-26 14:43 UTC, Muntasib-creator approved these changes

2023-06-26 14:44 UTC, merged