Optional parameter fix
AutomationSolutionz/Zeuz_Python_Node pull request #330
Opened 2023-06-12 14:20 UTC by Towshik

## PR Type

PR_TYPE

## PR Checklist
Fixed optional parameter's 'optional' word removal

- [x] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] A changelog entry has been made.
- [ ] Version number has been updated.
- [ ] Required modules have been added to respective "requirements*.txt" files.
- [x] Relevant Test Cases added to this description (below).
- [ ] (Team) Label with affected action categories and semver status.

## Overview

I was told to check if fixing optional parameter term is hampering the functionality of optional action, I checked it out briefly and it's still working as usual, getting passed always. I was also told to replace all the "optional option" with "optional parameter" as both being the same thing, so if someone uses an "optional option" it will get converted into "optional parameter" inside action handler and will work as "optional parameter" should do. The change was suggested by Muhib vai inside action handler.
This is also tested and is working fine so I put up the latest commit

## Test Cases
- [TEST-6883](https://zeuz.zeuz.ai/Home/ManageTestCases/Edit/TEST-6883/#parentHorizontalTab2)

2023-06-14 09:36 UTC, Muntasib-creator requested changes

2023-06-14 09:36 UTC, Muntasib-creator commented on Framework/Built_In_Automation/Mobile/CrossPlatform/Appium/BuiltInFunctions.py
> +            if mid in ("option", "optional parameter") and "x_offset:y_offset" in left:
`optional parameter` and `optional option` both need to be fixed

2023-06-19 12:34 UTC, sazid commented
@Towshik please describe the changes and their purpose. Also list out if there's any behavioural/breaking changes.

2023-06-19 12:54 UTC, Towshik commented
I was told to check if fixing optional parameter term is hampering the functionality of optional action, I checked it out briefly and it's still working as usual, getting passed always. I was also told to replace all the "optional option" with "optional parameter" as both being the same thing, so if someone uses an "optional option" it will get converted into "optional parameter" inside action handler and will work as "optional parameter" should do. The change was suggested by Muhib vai inside action handler.
This is also tested and is working fine

2023-06-26 14:41 UTC, Muntasib-creator approved these changes

2023-06-26 14:42 UTC, merged